{
 "cells": [
  {
   "cell_type": "markdown",
   "source": [
    "# This file is based on the data of hw3\n",
    "## We mainly do two things:\n",
    "-  Classify data\n",
    "- Train the regression model\n",
    "\n"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.10.8\n"
     ]
    }
   ],
   "source": [
    "# check python version\n",
    "# must be 3.8 to 3.10\n",
    "from platform import python_version\n",
    "\n",
    "print(python_version())"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting polygon-api-client\r\n",
      "  Using cached polygon_api_client-1.4.0-py3-none-any.whl (34 kB)\r\n",
      "Collecting certifi<2023.0.0,>=2022.5.18\r\n",
      "  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)\r\n",
      "Collecting websockets<11.0,>=10.3\r\n",
      "  Using cached websockets-10.4-cp310-cp310-macosx_10_9_x86_64.whl (97 kB)\r\n",
      "Collecting urllib3<2.0.0,>=1.26.9\r\n",
      "  Using cached urllib3-1.26.13-py2.py3-none-any.whl (140 kB)\r\n",
      "Installing collected packages: websockets, urllib3, certifi, polygon-api-client\r\n",
      "Successfully installed certifi-2022.9.24 polygon-api-client-1.4.0 urllib3-1.26.13 websockets-10.4\r\n",
      "\u001B[33mWARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n",
      "Collecting sqlalchemy\r\n",
      "  Using cached SQLAlchemy-1.4.44-cp310-cp310-macosx_10_15_x86_64.whl (1.6 MB)\r\n",
      "Collecting greenlet!=0.4.17\r\n",
      "  Using cached greenlet-2.0.1-cp310-cp310-macosx_10_15_x86_64.whl (203 kB)\r\n",
      "Installing collected packages: greenlet, sqlalchemy\r\n",
      "Successfully installed greenlet-2.0.1 sqlalchemy-1.4.44\r\n",
      "\u001B[33mWARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n",
      "Collecting pandas\r\n",
      "  Using cached pandas-1.5.2-cp310-cp310-macosx_10_9_x86_64.whl (12.0 MB)\r\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in ./venv/lib/python3.10/site-packages (from pandas) (2.8.2)\r\n",
      "Collecting pytz>=2020.1\r\n",
      "  Using cached pytz-2022.6-py2.py3-none-any.whl (498 kB)\r\n",
      "Collecting numpy>=1.21.0\r\n",
      "  Downloading numpy-1.23.5-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)\r\n",
      "     |████████████████████████████████| 18.1 MB 19.8 MB/s            \r\n",
      "\u001B[?25hRequirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)\r\n",
      "Installing collected packages: pytz, numpy, pandas\r\n",
      "Successfully installed numpy-1.23.5 pandas-1.5.2 pytz-2022.6\r\n",
      "\u001B[33mWARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n",
      "Collecting matplotlib\r\n",
      "  Using cached matplotlib-3.6.2-cp310-cp310-macosx_10_12_x86_64.whl (7.3 MB)\r\n",
      "Collecting kiwisolver>=1.0.1\r\n",
      "  Using cached kiwisolver-1.4.4-cp310-cp310-macosx_10_9_x86_64.whl (65 kB)\r\n",
      "Collecting pillow>=6.2.0\r\n",
      "  Using cached Pillow-9.3.0-cp310-cp310-macosx_10_10_x86_64.whl (3.3 MB)\r\n",
      "Requirement already satisfied: numpy>=1.19 in ./venv/lib/python3.10/site-packages (from matplotlib) (1.23.5)\r\n",
      "Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.10/site-packages (from matplotlib) (21.3)\r\n",
      "Collecting fonttools>=4.22.0\r\n",
      "  Using cached fonttools-4.38.0-py3-none-any.whl (965 kB)\r\n",
      "Requirement already satisfied: python-dateutil>=2.7 in ./venv/lib/python3.10/site-packages (from matplotlib) (2.8.2)\r\n",
      "Collecting contourpy>=1.0.1\r\n",
      "  Using cached contourpy-1.0.6-cp310-cp310-macosx_10_9_x86_64.whl (240 kB)\r\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in ./venv/lib/python3.10/site-packages (from matplotlib) (3.0.9)\r\n",
      "Collecting cycler>=0.10\r\n",
      "  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)\r\n",
      "Requirement already satisfied: six>=1.5 in ./venv/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)\r\n",
      "Installing collected packages: pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib\r\n",
      "Successfully installed contourpy-1.0.6 cycler-0.11.0 fonttools-4.38.0 kiwisolver-1.4.4 matplotlib-3.6.2 pillow-9.3.0\r\n",
      "\u001B[33mWARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n",
      "Collecting numpy==1.22.3\r\n",
      "  Using cached numpy-1.22.3-cp310-cp310-macosx_10_14_x86_64.whl (17.6 MB)\r\n",
      "Installing collected packages: numpy\r\n",
      "  Attempting uninstall: numpy\r\n",
      "    Found existing installation: numpy 1.23.5\r\n",
      "    Uninstalling numpy-1.23.5:\r\n",
      "      Successfully uninstalled numpy-1.23.5\r\n",
      "Successfully installed numpy-1.22.3\r\n",
      "\u001B[33mWARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n",
      "Collecting pycaret\r\n",
      "  Using cached pycaret-2.3.10-py3-none-any.whl (320 kB)\r\n",
      "Collecting wordcloud\r\n",
      "  Using cached wordcloud-1.8.2.2-cp310-cp310-macosx_10_9_x86_64.whl (160 kB)\r\n",
      "Requirement already satisfied: matplotlib in ./venv/lib/python3.10/site-packages (from pycaret) (3.6.2)\r\n",
      "Collecting yellowbrick>=1.0.1\r\n",
      "  Using cached yellowbrick-1.5-py3-none-any.whl (282 kB)\r\n",
      "Collecting scikit-learn==0.23.2\r\n",
      "  Using cached scikit-learn-0.23.2.tar.gz (7.2 MB)\r\n",
      "  Installing build dependencies ... \u001B[?25lerror\r\n",
      "\u001B[31m  ERROR: Command errored out with exit status 1:\r\n",
      "   command: '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python' /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-standalone-pip-w6agj451/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-build-env-ewn_vm9m/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation == '\"'\"'CPython'\"'\"'' 'numpy==1.14.0; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation != '\"'\"'CPython'\"'\"'' 'numpy==1.14.5; python_version=='\"'\"'3.7'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.6'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.7'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'scipy>=0.19.1'\r\n",
      "       cwd: None\r\n",
      "  Complete output (438 lines):\r\n",
      "  Ignoring numpy: markers 'python_version == \"3.6\" and platform_system != \"AIX\" and platform_python_implementation == \"CPython\"' don't match your environment\r\n",
      "  Ignoring numpy: markers 'python_version == \"3.6\" and platform_system != \"AIX\" and platform_python_implementation != \"CPython\"' don't match your environment\r\n",
      "  Ignoring numpy: markers 'python_version == \"3.7\" and platform_system != \"AIX\"' don't match your environment\r\n",
      "  Ignoring numpy: markers 'python_version == \"3.6\" and platform_system == \"AIX\"' don't match your environment\r\n",
      "  Ignoring numpy: markers 'python_version == \"3.7\" and platform_system == \"AIX\"' don't match your environment\r\n",
      "  Ignoring numpy: markers 'python_version >= \"3.8\" and platform_system == \"AIX\"' don't match your environment\r\n",
      "  Collecting setuptools\r\n",
      "    Using cached setuptools-65.6.3-py3-none-any.whl (1.2 MB)\r\n",
      "  Collecting wheel\r\n",
      "    Using cached wheel-0.38.4-py3-none-any.whl (36 kB)\r\n",
      "  Collecting Cython>=0.28.5\r\n",
      "    Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)\r\n",
      "  Collecting numpy==1.17.3\r\n",
      "    Using cached numpy-1.17.3.zip (6.4 MB)\r\n",
      "    Preparing metadata (setup.py): started\r\n",
      "    Preparing metadata (setup.py): finished with status 'done'\r\n",
      "  Collecting scipy>=0.19.1\r\n",
      "    Using cached scipy-1.9.3-cp310-cp310-macosx_10_9_x86_64.whl (34.3 MB)\r\n",
      "    Using cached scipy-1.9.2-cp310-cp310-macosx_10_9_x86_64.whl (34.2 MB)\r\n",
      "    Using cached scipy-1.9.1-cp310-cp310-macosx_12_0_universal2.macosx_10_9_x86_64.whl (58.4 MB)\r\n",
      "    Using cached scipy-1.9.0-cp310-cp310-macosx_12_0_universal2.macosx_10_9_x86_64.whl (58.4 MB)\r\n",
      "    Using cached scipy-1.8.1-cp310-cp310-macosx_12_0_universal2.macosx_10_9_x86_64.whl (55.7 MB)\r\n",
      "  Building wheels for collected packages: numpy\r\n",
      "    Building wheel for numpy (setup.py): started\r\n",
      "    Building wheel for numpy (setup.py): finished with status 'error'\r\n",
      "    ERROR: Command errored out with exit status 1:\r\n",
      "     command: '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-wheel-tmrp8qo0\r\n",
      "         cwd: /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/\r\n",
      "    Complete output (186 lines):\r\n",
      "    Running from numpy source directory.\r\n",
      "    svnversion: error: The subversion command line tools are no longer provided by Xcode.\r\n",
      "    non-existing path in 'numpy/distutils': 'site.cfg'\r\n",
      "    /Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'\r\n",
      "      warnings.warn(msg)\r\n",
      "    running bdist_wheel\r\n",
      "    running build\r\n",
      "    running config_cc\r\n",
      "    running config_fc\r\n",
      "    running build_src\r\n",
      "    creating build\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy/distutils\r\n",
      "    Could not locate executable gfortran\r\n",
      "    Could not locate executable f95\r\n",
      "    Could not locate executable f90\r\n",
      "    Could not locate executable f77\r\n",
      "    Could not locate executable xlf90\r\n",
      "    Could not locate executable xlf\r\n",
      "    Could not locate executable ifort\r\n",
      "    Could not locate executable ifc\r\n",
      "    Could not locate executable g77\r\n",
      "    Could not locate executable g95\r\n",
      "    Could not locate executable pgfortran\r\n",
      "    don't know how to compile Fortran code on platform 'posix'\r\n",
      "    _configtest.c:1:5: warning: incompatible redeclaration of library function 'exp' [-Wincompatible-library-redeclaration]\r\n",
      "    int exp (void);\r\n",
      "        ^\r\n",
      "    _configtest.c:1:5: note: 'exp' is a builtin with type 'double (double)'\r\n",
      "    1 warning generated.\r\n",
      "    _configtest.c:1:5: warning: incompatible redeclaration of library function 'exp' [-Wincompatible-library-redeclaration]\r\n",
      "    int exp (void);\r\n",
      "        ^\r\n",
      "    _configtest.c:1:5: note: 'exp' is a builtin with type 'double (double)'\r\n",
      "    1 warning generated.\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy/core\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy/core/src\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy/core/src/npymath\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy/core/src/common\r\n",
      "    creating build/src.macosx-10.9-universal2-3.1/numpy/core/src/npysort\r\n",
      "    In file included from _configtest.c:1:\r\n",
      "    In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:11:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:63:\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture\r\n",
      "    #error Unsupported architecture\r\n",
      "     ^\r\n",
      "    In file included from _configtest.c:1:\r\n",
      "    In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:11:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:64:\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported\r\n",
      "    #error architecture not supported\r\n",
      "     ^\r\n",
      "    In file included from _configtest.c:1:\r\n",
      "    In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported\r\n",
      "    #error architecture not supported\r\n",
      "     ^\r\n",
      "    In file included from _configtest.c:1:\r\n",
      "    In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'\r\n",
      "    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */\r\n",
      "            ^\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */\r\n",
      "            ^\r\n",
      "    note: '__int128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "    typedef __int32_t       __darwin_dev_t;         /* dev_t */\r\n",
      "            ^\r\n",
      "    note: '__int128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'\r\n",
      "    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */\r\n",
      "            ^\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'\r\n",
      "    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */\r\n",
      "            ^\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'\r\n",
      "    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */\r\n",
      "            ^\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */\r\n",
      "            ^\r\n",
      "    note: '__int128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */\r\n",
      "            ^\r\n",
      "    note: '__int128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    In file included from _configtest.c:1:\r\n",
      "    In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "    typedef __uint32_t      __darwin_wctype_t;\r\n",
      "            ^\r\n",
      "    note: '__uint128_t' declared here\r\n",
      "    In file included from _configtest.c:1:\r\n",
      "    In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:\r\n",
      "    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:\r\n",
      "    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported\r\n",
      "    #error architecture not supported\r\n",
      "     ^\r\n",
      "    fatal error: too many errors emitted, stopping now [-ferror-limit=]\r\n",
      "    20 errors generated.\r\n",
      "    Traceback (most recent call last):\r\n",
      "      File \"<string>\", line 1, in <module>\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py\", line 443, in <module>\r\n",
      "        setup_package()\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py\", line 435, in setup_package\r\n",
      "        setup(**metadata)\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/core.py\", line 171, in setup\r\n",
      "        return old_setup(**new_attr)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/__init__.py\", line 155, in setup\r\n",
      "        return distutils.core.setup(**attrs)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 148, in setup\r\n",
      "        return run_commands(dist)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 163, in run_commands\r\n",
      "        dist.run_commands()\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 967, in run_commands\r\n",
      "        self.run_command(cmd)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "        cmd_obj.run()\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/wheel/bdist_wheel.py\", line 299, in run\r\n",
      "        self.run_command('build')\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py\", line 313, in run_command\r\n",
      "        self.distribution.run_command(command)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "        cmd_obj.run()\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build.py\", line 47, in run\r\n",
      "        old_build.run(self)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py\", line 135, in run\r\n",
      "        self.run_command(cmd_name)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py\", line 313, in run_command\r\n",
      "        self.distribution.run_command(command)\r\n",
      "      File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "        cmd_obj.run()\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 142, in run\r\n",
      "        self.build_sources()\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 159, in build_sources\r\n",
      "        self.build_extension_sources(ext)\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 316, in build_extension_sources\r\n",
      "        sources = self.generate_sources(sources, ext)\r\n",
      "      File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 369, in generate_sources\r\n",
      "        source = func(extension, build_dir)\r\n",
      "      File \"numpy/core/setup.py\", line 430, in generate_config_h\r\n",
      "        moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)\r\n",
      "      File \"numpy/core/setup.py\", line 49, in check_types\r\n",
      "        out = check_types(*a, **kw)\r\n",
      "      File \"numpy/core/setup.py\", line 286, in check_types\r\n",
      "        raise SystemError(\r\n",
      "    SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.\r\n",
      "    ----------------------------------------\r\n",
      "    ERROR: Failed building wheel for numpy\r\n",
      "    Running setup.py clean for numpy\r\n",
      "    ERROR: Command errored out with exit status 1:\r\n",
      "     command: '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' clean --all\r\n",
      "         cwd: /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce\r\n",
      "    Complete output (10 lines):\r\n",
      "    Running from numpy source directory.\r\n",
      "  \r\n",
      "    `setup.py clean` is not supported, use one of the following instead:\r\n",
      "  \r\n",
      "      - `git clean -xdf` (cleans all files)\r\n",
      "      - `git clean -Xdf` (cleans all versioned files, doesn't touch\r\n",
      "                          files that aren't checked into the git repo)\r\n",
      "  \r\n",
      "    Add `--force` to your command to use it anyway if you must (unsupported).\r\n",
      "  \r\n",
      "    ----------------------------------------\r\n",
      "    ERROR: Failed cleaning build dir for numpy\r\n",
      "  Failed to build numpy\r\n",
      "  Installing collected packages: numpy, wheel, setuptools, scipy, Cython\r\n",
      "      Running setup.py install for numpy: started\r\n",
      "      Running setup.py install for numpy: finished with status 'error'\r\n",
      "      ERROR: Command errored out with exit status 1:\r\n",
      "       command: '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-record-8a87wd6m/install-record.txt --single-version-externally-managed --prefix /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-build-env-ewn_vm9m/overlay --compile --install-headers /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-build-env-ewn_vm9m/overlay/include/site/python3.10/numpy\r\n",
      "           cwd: /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/\r\n",
      "      Complete output (192 lines):\r\n",
      "      Running from numpy source directory.\r\n",
      "  \r\n",
      "      Note: if you need reliable uninstall behavior, then install\r\n",
      "      with pip instead of using `setup.py install`:\r\n",
      "  \r\n",
      "        - `pip install .`       (from a git repo or downloaded source\r\n",
      "                                 release)\r\n",
      "        - `pip install numpy`   (last NumPy release on PyPi)\r\n",
      "  \r\n",
      "  \r\n",
      "      svnversion: error: The subversion command line tools are no longer provided by Xcode.\r\n",
      "      non-existing path in 'numpy/distutils': 'site.cfg'\r\n",
      "      /Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'\r\n",
      "        warnings.warn(msg)\r\n",
      "      running install\r\n",
      "      /Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\r\n",
      "        warnings.warn(\r\n",
      "      running build\r\n",
      "      running config_cc\r\n",
      "      running config_fc\r\n",
      "      running build_src\r\n",
      "      Could not locate executable gfortran\r\n",
      "      Could not locate executable f95\r\n",
      "      Could not locate executable f90\r\n",
      "      Could not locate executable f77\r\n",
      "      Could not locate executable xlf90\r\n",
      "      Could not locate executable xlf\r\n",
      "      Could not locate executable ifort\r\n",
      "      Could not locate executable ifc\r\n",
      "      Could not locate executable g77\r\n",
      "      Could not locate executable g95\r\n",
      "      Could not locate executable pgfortran\r\n",
      "      don't know how to compile Fortran code on platform 'posix'\r\n",
      "      _configtest.c:1:5: warning: incompatible redeclaration of library function 'exp' [-Wincompatible-library-redeclaration]\r\n",
      "      int exp (void);\r\n",
      "          ^\r\n",
      "      _configtest.c:1:5: note: 'exp' is a builtin with type 'double (double)'\r\n",
      "      1 warning generated.\r\n",
      "      _configtest.c:1:5: warning: incompatible redeclaration of library function 'exp' [-Wincompatible-library-redeclaration]\r\n",
      "      int exp (void);\r\n",
      "          ^\r\n",
      "      _configtest.c:1:5: note: 'exp' is a builtin with type 'double (double)'\r\n",
      "      1 warning generated.\r\n",
      "      In file included from _configtest.c:1:\r\n",
      "      In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:11:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:63:\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture\r\n",
      "      #error Unsupported architecture\r\n",
      "       ^\r\n",
      "      In file included from _configtest.c:1:\r\n",
      "      In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:11:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:64:\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported\r\n",
      "      #error architecture not supported\r\n",
      "       ^\r\n",
      "      In file included from _configtest.c:1:\r\n",
      "      In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported\r\n",
      "      #error architecture not supported\r\n",
      "       ^\r\n",
      "      In file included from _configtest.c:1:\r\n",
      "      In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'\r\n",
      "      typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */\r\n",
      "              ^\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "      typedef __int32_t       __darwin_blksize_t;     /* preferred block size */\r\n",
      "              ^\r\n",
      "      note: '__int128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "      typedef __int32_t       __darwin_dev_t;         /* dev_t */\r\n",
      "              ^\r\n",
      "      note: '__int128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'\r\n",
      "      typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */\r\n",
      "              ^\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'\r\n",
      "      typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */\r\n",
      "              ^\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'\r\n",
      "      typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */\r\n",
      "              ^\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "      typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */\r\n",
      "              ^\r\n",
      "      note: '__int128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?\r\n",
      "      typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */\r\n",
      "              ^\r\n",
      "      note: '__int128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      In file included from _configtest.c:1:\r\n",
      "      In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?\r\n",
      "      typedef __uint32_t      __darwin_wctype_t;\r\n",
      "              ^\r\n",
      "      note: '__uint128_t' declared here\r\n",
      "      In file included from _configtest.c:1:\r\n",
      "      In file included from /Library/Frameworks/Python.framework/Versions/3.10/include/python3.10/Python.h:25:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:\r\n",
      "      In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:\r\n",
      "      /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported\r\n",
      "      #error architecture not supported\r\n",
      "       ^\r\n",
      "      fatal error: too many errors emitted, stopping now [-ferror-limit=]\r\n",
      "      20 errors generated.\r\n",
      "      Traceback (most recent call last):\r\n",
      "        File \"<string>\", line 1, in <module>\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py\", line 443, in <module>\r\n",
      "          setup_package()\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py\", line 435, in setup_package\r\n",
      "          setup(**metadata)\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/core.py\", line 171, in setup\r\n",
      "          return old_setup(**new_attr)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/__init__.py\", line 155, in setup\r\n",
      "          return distutils.core.setup(**attrs)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 148, in setup\r\n",
      "          return run_commands(dist)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py\", line 163, in run_commands\r\n",
      "          dist.run_commands()\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 967, in run_commands\r\n",
      "          self.run_command(cmd)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "          cmd_obj.run()\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/install.py\", line 62, in run\r\n",
      "          r = self.setuptools_run()\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/install.py\", line 36, in setuptools_run\r\n",
      "          return distutils_install.run(self)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/command/install.py\", line 662, in run\r\n",
      "          self.run_command('build')\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py\", line 313, in run_command\r\n",
      "          self.distribution.run_command(command)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "          cmd_obj.run()\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build.py\", line 47, in run\r\n",
      "          old_build.run(self)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py\", line 135, in run\r\n",
      "          self.run_command(cmd_name)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py\", line 313, in run_command\r\n",
      "          self.distribution.run_command(command)\r\n",
      "        File \"/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py\", line 986, in run_command\r\n",
      "          cmd_obj.run()\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 142, in run\r\n",
      "          self.build_sources()\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 159, in build_sources\r\n",
      "          self.build_extension_sources(ext)\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 316, in build_extension_sources\r\n",
      "          sources = self.generate_sources(sources, ext)\r\n",
      "        File \"/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/numpy/distutils/command/build_src.py\", line 369, in generate_sources\r\n",
      "          source = func(extension, build_dir)\r\n",
      "        File \"numpy/core/setup.py\", line 430, in generate_config_h\r\n",
      "          moredefs, ignored = cocache.check_types(config_cmd, ext, build_dir)\r\n",
      "        File \"numpy/core/setup.py\", line 49, in check_types\r\n",
      "          out = check_types(*a, **kw)\r\n",
      "        File \"numpy/core/setup.py\", line 286, in check_types\r\n",
      "          raise SystemError(\r\n",
      "      SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.\r\n",
      "      ----------------------------------------\r\n",
      "  ERROR: Command errored out with exit status 1: '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-install-m7kk2frh/numpy_bfdfb6fb94274da3b38faf78891163ce/setup.py'\"'\"';f = getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__) if os.path.exists(__file__) else io.StringIO('\"'\"'from setuptools import setup; setup()'\"'\"');code = f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-record-8a87wd6m/install-record.txt --single-version-externally-managed --prefix /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-build-env-ewn_vm9m/overlay --compile --install-headers /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-build-env-ewn_vm9m/overlay/include/site/python3.10/numpy Check the logs for full command output.\r\n",
      "  WARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "  You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\r\n",
      "  ----------------------------------------\u001B[0m\r\n",
      "\u001B[33mWARNING: Discarding https://files.pythonhosted.org/packages/aa/f6/75297be19f48b7a8c2577753a3a700f98fc4db49d0e5ed3820dd8dee43d4/scikit-learn-0.23.2.tar.gz#sha256=20766f515e6cd6f954554387dfae705d93c7b544ec0e6c6a5d8e006f6f7ef480 (from https://pypi.org/simple/scikit-learn/) (requires-python:>=3.6). Command errored out with exit status 1: '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python' /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-standalone-pip-w6agj451/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /private/var/folders/7t/x2z58zlx6nldqfzsvjv_sb000000gn/T/pip-build-env-ewn_vm9m/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'Cython>=0.28.5' 'numpy==1.13.3; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation == '\"'\"'CPython'\"'\"'' 'numpy==1.14.0; python_version=='\"'\"'3.6'\"'\"' and platform_system!='\"'\"'AIX'\"'\"' and platform_python_implementation != '\"'\"'CPython'\"'\"'' 'numpy==1.14.5; python_version=='\"'\"'3.7'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system!='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.6'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.16.0; python_version=='\"'\"'3.7'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'numpy==1.17.3; python_version>='\"'\"'3.8'\"'\"' and platform_system=='\"'\"'AIX'\"'\"'' 'scipy>=0.19.1' Check the logs for full command output.\u001B[0m\r\n",
      "\u001B[?25hCollecting pycaret\r\n",
      "  Using cached pycaret-2.3.9-py3-none-any.whl (319 kB)\r\n",
      "  Using cached pycaret-2.3.8-py3-none-any.whl (318 kB)\r\n",
      "  Using cached pycaret-2.3.7-py3-none-any.whl (318 kB)\r\n",
      "  Using cached pycaret-2.3.6-py3-none-any.whl (301 kB)\r\n",
      "  Using cached pycaret-2.3.5-py3-none-any.whl (288 kB)\r\n",
      "  Using cached pycaret-2.3.4-py3-none-any.whl (266 kB)\r\n",
      "  Using cached pycaret-2.3.3-py3-none-any.whl (264 kB)\r\n",
      "  Using cached pycaret-2.3.2-py3-none-any.whl (263 kB)\r\n",
      "  Using cached pycaret-2.3.1-py3-none-any.whl (261 kB)\r\n",
      "  Using cached pycaret-2.3.0-py3-none-any.whl (261 kB)\r\n",
      "  Using cached pycaret-2.2.3-py3-none-any.whl (249 kB)\r\n",
      "  Using cached pycaret-2.2.2-py3-none-any.whl (249 kB)\r\n",
      "Requirement already satisfied: IPython in ./venv/lib/python3.10/site-packages (from pycaret) (8.7.0)\r\n",
      "Collecting mlflow\r\n",
      "  Using cached mlflow-2.0.1-py3-none-any.whl (16.5 MB)\r\n",
      "Collecting plotly>=4.4.1\r\n",
      "  Using cached plotly-5.11.0-py2.py3-none-any.whl (15.3 MB)\r\n",
      "Collecting pandas-profiling>=2.8.0\r\n",
      "  Using cached pandas_profiling-3.5.0-py2.py3-none-any.whl (325 kB)\r\n",
      "Collecting spacy\r\n",
      "  Using cached spacy-3.4.3-cp310-cp310-macosx_10_9_x86_64.whl (6.7 MB)\r\n",
      "Requirement already satisfied: ipywidgets in ./venv/lib/python3.10/site-packages (from pycaret) (8.0.2)\r\n",
      "Collecting catboost>=0.23.2\r\n",
      "  Using cached catboost-1.1.1-cp310-none-macosx_10_6_universal2.whl (22.0 MB)\r\n",
      "Requirement already satisfied: numpy>=1.17 in ./venv/lib/python3.10/site-packages (from pycaret) (1.22.3)\r\n",
      "Collecting joblib\r\n",
      "  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)\r\n",
      "Collecting seaborn\r\n",
      "  Using cached seaborn-0.12.1-py3-none-any.whl (288 kB)\r\n",
      "Collecting umap-learn\r\n",
      "  Using cached umap_learn-0.5.3-py3-none-any.whl\r\n",
      "Collecting xgboost>=1.1.0\r\n",
      "  Using cached xgboost-1.7.1-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl (1.8 MB)\r\n",
      "Collecting pyod\r\n",
      "  Using cached pyod-1.0.6-py3-none-any.whl\r\n",
      "Requirement already satisfied: pandas in ./venv/lib/python3.10/site-packages (from pycaret) (1.5.2)\r\n",
      "Collecting mlxtend\r\n",
      "  Using cached mlxtend-0.21.0-py2.py3-none-any.whl (1.3 MB)\r\n",
      "Collecting textblob\r\n",
      "  Using cached textblob-0.17.1-py2.py3-none-any.whl (636 kB)\r\n",
      "Collecting lightgbm>=2.3.1\r\n",
      "  Using cached lightgbm-3.3.3-py3-none-macosx_10_15_x86_64.macosx_11_6_x86_64.macosx_12_0_x86_64.whl (1.3 MB)\r\n",
      "Collecting scikit-plot\r\n",
      "  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)\r\n",
      "Collecting pyLDAvis\r\n",
      "  Using cached pyLDAvis-3.3.1-py2.py3-none-any.whl\r\n",
      "Collecting scikit-learn>=0.23.2\r\n",
      "  Using cached scikit_learn-1.1.3-cp310-cp310-macosx_10_9_x86_64.whl (8.7 MB)\r\n",
      "Collecting kmodes>=0.10.1\r\n",
      "  Using cached kmodes-0.12.2-py2.py3-none-any.whl (20 kB)\r\n",
      "Collecting gensim\r\n",
      "  Using cached gensim-4.2.0-cp310-cp310-macosx_10_9_universal2.whl (24.4 MB)\r\n",
      "Collecting imbalanced-learn>=0.7.0\r\n",
      "  Using cached imbalanced_learn-0.9.1-py3-none-any.whl (199 kB)\r\n",
      "Collecting nltk\r\n",
      "  Using cached nltk-3.7-py3-none-any.whl (1.5 MB)\r\n",
      "Collecting cufflinks>=0.17.0\r\n",
      "  Using cached cufflinks-0.17.3-py3-none-any.whl\r\n",
      "Collecting graphviz\r\n",
      "  Using cached graphviz-0.20.1-py3-none-any.whl (47 kB)\r\n",
      "Requirement already satisfied: six in ./venv/lib/python3.10/site-packages (from catboost>=0.23.2->pycaret) (1.16.0)\r\n",
      "Collecting scipy\r\n",
      "  Using cached scipy-1.9.3-cp310-cp310-macosx_10_9_x86_64.whl (34.3 MB)\r\n",
      "Requirement already satisfied: setuptools>=34.4.1 in ./venv/lib/python3.10/site-packages (from cufflinks>=0.17.0->pycaret) (60.2.0)\r\n",
      "Collecting colorlover>=0.2.1\r\n",
      "  Using cached colorlover-0.3.0-py3-none-any.whl (8.9 kB)\r\n",
      "Collecting threadpoolctl>=2.0.0\r\n",
      "  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)\r\n",
      "Requirement already satisfied: jedi>=0.16 in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (0.18.2)\r\n",
      "Requirement already satisfied: pickleshare in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (0.7.5)\r\n",
      "Requirement already satisfied: pygments>=2.4.0 in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (2.13.0)\r\n",
      "Requirement already satisfied: backcall in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (0.2.0)\r\n",
      "Requirement already satisfied: traitlets>=5 in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (5.6.0)\r\n",
      "Requirement already satisfied: stack-data in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (0.6.2)\r\n",
      "Requirement already satisfied: decorator in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (5.1.1)\r\n",
      "Requirement already satisfied: pexpect>4.3 in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (4.8.0)\r\n",
      "Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.11 in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (3.0.33)\r\n",
      "Requirement already satisfied: appnope in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (0.1.3)\r\n",
      "Requirement already satisfied: matplotlib-inline in ./venv/lib/python3.10/site-packages (from IPython->pycaret) (0.1.6)\r\n",
      "Requirement already satisfied: ipykernel>=4.5.1 in ./venv/lib/python3.10/site-packages (from ipywidgets->pycaret) (6.17.1)\r\n",
      "Requirement already satisfied: jupyterlab-widgets~=3.0 in ./venv/lib/python3.10/site-packages (from ipywidgets->pycaret) (3.0.3)\r\n",
      "Requirement already satisfied: widgetsnbextension~=4.0 in ./venv/lib/python3.10/site-packages (from ipywidgets->pycaret) (4.0.3)\r\n",
      "Requirement already satisfied: wheel in ./venv/lib/python3.10/site-packages (from lightgbm>=2.3.1->pycaret) (0.37.1)\r\n",
      "Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.10/site-packages (from pandas->pycaret) (2022.6)\r\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in ./venv/lib/python3.10/site-packages (from pandas->pycaret) (2.8.2)\r\n",
      "Collecting tqdm<4.65,>=4.48.2\r\n",
      "  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)\r\n",
      "Collecting multimethod<1.10,>=1.4\r\n",
      "  Using cached multimethod-1.9-py3-none-any.whl (10 kB)\r\n",
      "Collecting typeguard<2.14,>=2.13.2\r\n",
      "  Using cached typeguard-2.13.3-py3-none-any.whl (17 kB)\r\n",
      "Collecting pydantic<1.11,>=1.8.1\r\n",
      "  Using cached pydantic-1.10.2-cp310-cp310-macosx_10_9_x86_64.whl (3.1 MB)\r\n",
      "Collecting requests<2.29,>=2.24.0\r\n",
      "  Using cached requests-2.28.1-py3-none-any.whl (62 kB)\r\n",
      "Collecting phik<0.13,>=0.11.1\r\n",
      "  Using cached phik-0.12.2-cp310-cp310-macosx_10_13_x86_64.whl (812 kB)\r\n",
      "Requirement already satisfied: jinja2<3.2,>=2.11.1 in ./venv/lib/python3.10/site-packages (from pandas-profiling>=2.8.0->pycaret) (3.1.2)\r\n",
      "Collecting PyYAML<6.1,>=5.0.0\r\n",
      "  Using cached PyYAML-6.0-cp310-cp310-macosx_10_9_x86_64.whl (197 kB)\r\n",
      "Collecting statsmodels<0.14,>=0.13.2\r\n",
      "  Using cached statsmodels-0.13.5-cp310-cp310-macosx_10_9_x86_64.whl (9.7 MB)\r\n",
      "Collecting visions[type_image_path]==0.7.5\r\n",
      "  Using cached visions-0.7.5-py3-none-any.whl (102 kB)\r\n",
      "Collecting htmlmin==0.1.12\r\n",
      "  Using cached htmlmin-0.1.12-py3-none-any.whl\r\n",
      "Requirement already satisfied: attrs>=19.3.0 in ./venv/lib/python3.10/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret) (22.1.0)\r\n",
      "Collecting tangled-up-in-unicode>=0.0.4\r\n",
      "  Using cached tangled_up_in_unicode-0.2.0-py3-none-any.whl (4.7 MB)\r\n",
      "Collecting networkx>=2.4\r\n",
      "  Using cached networkx-2.8.8-py3-none-any.whl (2.0 MB)\r\n",
      "Requirement already satisfied: Pillow in ./venv/lib/python3.10/site-packages (from visions[type_image_path]==0.7.5->pandas-profiling>=2.8.0->pycaret) (9.3.0)\r\n",
      "Collecting imagehash\r\n",
      "  Using cached ImageHash-4.3.1-py2.py3-none-any.whl (296 kB)\r\n",
      "Requirement already satisfied: pyparsing>=2.2.1 in ./venv/lib/python3.10/site-packages (from matplotlib->pycaret) (3.0.9)\r\n",
      "Requirement already satisfied: packaging>=20.0 in ./venv/lib/python3.10/site-packages (from matplotlib->pycaret) (21.3)\r\n",
      "Requirement already satisfied: contourpy>=1.0.1 in ./venv/lib/python3.10/site-packages (from matplotlib->pycaret) (1.0.6)\r\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in ./venv/lib/python3.10/site-packages (from matplotlib->pycaret) (1.4.4)\r\n",
      "Requirement already satisfied: cycler>=0.10 in ./venv/lib/python3.10/site-packages (from matplotlib->pycaret) (0.11.0)\r\n",
      "Requirement already satisfied: fonttools>=4.22.0 in ./venv/lib/python3.10/site-packages (from matplotlib->pycaret) (4.38.0)\r\n",
      "Collecting tenacity>=6.2.0\r\n",
      "  Using cached tenacity-8.1.0-py3-none-any.whl (23 kB)\r\n",
      "Collecting smart-open>=1.8.1\r\n",
      "  Using cached smart_open-6.2.0-py3-none-any.whl (58 kB)\r\n",
      "Collecting cloudpickle<3\r\n",
      "  Using cached cloudpickle-2.2.0-py3-none-any.whl (25 kB)\r\n",
      "Requirement already satisfied: entrypoints<1 in ./venv/lib/python3.10/site-packages (from mlflow->pycaret) (0.4)\r\n",
      "Collecting gunicorn<21\r\n",
      "  Using cached gunicorn-20.1.0-py3-none-any.whl (79 kB)\r\n",
      "Collecting gitpython<4,>=2.1.0\r\n",
      "  Using cached GitPython-3.1.29-py3-none-any.whl (182 kB)\r\n",
      "Collecting importlib-metadata!=4.7.0,<6,>=3.7.0\r\n",
      "  Using cached importlib_metadata-5.1.0-py3-none-any.whl (21 kB)\r\n",
      "Collecting shap<1,>=0.40\r\n",
      "  Using cached shap-0.41.0-cp310-cp310-macosx_10_9_x86_64.whl (436 kB)\r\n",
      "Collecting pyarrow<11,>=4.0.0\r\n",
      "  Using cached pyarrow-10.0.1-cp310-cp310-macosx_10_14_x86_64.whl (25.0 MB)\r\n",
      "Collecting Flask<3\r\n",
      "  Using cached Flask-2.2.2-py3-none-any.whl (101 kB)\r\n",
      "Collecting docker<7,>=4.0.0\r\n",
      "  Using cached docker-6.0.1-py3-none-any.whl (147 kB)\r\n",
      "Collecting protobuf<5,>=3.12.0\r\n",
      "  Using cached protobuf-4.21.10-cp37-abi3-macosx_10_9_universal2.whl (483 kB)\r\n",
      "Collecting databricks-cli<1,>=0.8.7\r\n",
      "  Using cached databricks_cli-0.17.3-py3-none-any.whl\r\n",
      "Requirement already satisfied: sqlalchemy<2,>=1.4.0 in ./venv/lib/python3.10/site-packages (from mlflow->pycaret) (1.4.44)\r\n",
      "Collecting click<9,>=7.0\r\n",
      "  Using cached click-8.1.3-py3-none-any.whl (96 kB)\r\n",
      "Collecting sqlparse<1,>=0.4.0\r\n",
      "  Using cached sqlparse-0.4.3-py3-none-any.whl (42 kB)\r\n",
      "Collecting markdown<4,>=3.3\r\n",
      "  Using cached Markdown-3.4.1-py3-none-any.whl (93 kB)\r\n",
      "Collecting alembic<2\r\n",
      "  Using cached alembic-1.8.1-py3-none-any.whl (209 kB)\r\n",
      "Collecting querystring-parser<2\r\n",
      "  Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)\r\n",
      "Collecting regex>=2021.8.3\r\n",
      "  Using cached regex-2022.10.31-cp310-cp310-macosx_10_9_x86_64.whl (293 kB)\r\n",
      "Collecting sklearn\r\n",
      "  Using cached sklearn-0.0.post1-py3-none-any.whl\r\n",
      "Collecting future\r\n",
      "  Using cached future-0.18.2-py3-none-any.whl\r\n",
      "Collecting funcy\r\n",
      "  Using cached funcy-1.17-py2.py3-none-any.whl (33 kB)\r\n",
      "Collecting numexpr\r\n",
      "  Using cached numexpr-2.8.4-cp310-cp310-macosx_10_9_x86_64.whl (99 kB)\r\n",
      "Collecting numba>=0.51\r\n",
      "  Using cached numba-0.56.4-cp310-cp310-macosx_10_14_x86_64.whl (2.4 MB)\r\n",
      "Collecting spacy-legacy<3.1.0,>=3.0.10\r\n",
      "  Using cached spacy_legacy-3.0.10-py2.py3-none-any.whl (21 kB)\r\n",
      "Collecting typer<0.8.0,>=0.3.0\r\n",
      "  Using cached typer-0.7.0-py3-none-any.whl (38 kB)\r\n",
      "Collecting pathy>=0.3.5\r\n",
      "  Using cached pathy-0.10.0-py3-none-any.whl (48 kB)\r\n",
      "Collecting spacy-loggers<2.0.0,>=1.0.0\r\n",
      "  Using cached spacy_loggers-1.0.3-py3-none-any.whl (9.3 kB)\r\n",
      "Collecting thinc<8.2.0,>=8.1.0\r\n",
      "  Using cached thinc-8.1.5-cp310-cp310-macosx_10_9_x86_64.whl (761 kB)\r\n",
      "Collecting langcodes<4.0.0,>=3.2.0\r\n",
      "  Using cached langcodes-3.3.0-py3-none-any.whl (181 kB)\r\n",
      "Collecting wasabi<1.1.0,>=0.9.1\r\n",
      "  Using cached wasabi-0.10.1-py3-none-any.whl (26 kB)\r\n",
      "Collecting srsly<3.0.0,>=2.4.3\r\n",
      "  Using cached srsly-2.4.5-cp310-cp310-macosx_10_9_x86_64.whl (491 kB)\r\n",
      "Collecting catalogue<2.1.0,>=2.0.6\r\n",
      "  Using cached catalogue-2.0.8-py3-none-any.whl (17 kB)\r\n",
      "Collecting cymem<2.1.0,>=2.0.2\r\n",
      "  Using cached cymem-2.0.7-cp310-cp310-macosx_10_9_x86_64.whl (32 kB)\r\n",
      "Collecting murmurhash<1.1.0,>=0.28.0\r\n",
      "  Using cached murmurhash-1.0.9-cp310-cp310-macosx_10_9_x86_64.whl (18 kB)\r\n",
      "Collecting preshed<3.1.0,>=3.0.2\r\n",
      "  Using cached preshed-3.0.8-cp310-cp310-macosx_10_9_x86_64.whl (106 kB)\r\n",
      "Collecting pynndescent>=0.5\r\n",
      "  Using cached pynndescent-0.5.8-py3-none-any.whl\r\n",
      "Collecting Mako\r\n",
      "  Using cached Mako-1.2.4-py3-none-any.whl (78 kB)\r\n",
      "Collecting pyjwt>=1.7.0\r\n",
      "  Using cached PyJWT-2.6.0-py3-none-any.whl (20 kB)\r\n",
      "Collecting oauthlib>=3.1.0\r\n",
      "  Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)\r\n",
      "Collecting tabulate>=0.7.7\r\n",
      "  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)\r\n",
      "Requirement already satisfied: urllib3>=1.26.0 in ./venv/lib/python3.10/site-packages (from docker<7,>=4.0.0->mlflow->pycaret) (1.26.13)\r\n",
      "Requirement already satisfied: websocket-client>=0.32.0 in ./venv/lib/python3.10/site-packages (from docker<7,>=4.0.0->mlflow->pycaret) (1.4.2)\r\n",
      "Collecting itsdangerous>=2.0\r\n",
      "  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)\r\n",
      "Collecting Werkzeug>=2.2.2\r\n",
      "  Using cached Werkzeug-2.2.2-py3-none-any.whl (232 kB)\r\n",
      "Collecting gitdb<5,>=4.0.1\r\n",
      "  Using cached gitdb-4.0.10-py3-none-any.whl (62 kB)\r\n",
      "Collecting zipp>=0.5\r\n",
      "  Using cached zipp-3.11.0-py3-none-any.whl (6.6 kB)\r\n",
      "Requirement already satisfied: nest-asyncio in ./venv/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.5.6)\r\n",
      "Requirement already satisfied: psutil in ./venv/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (5.9.4)\r\n",
      "Requirement already satisfied: tornado>=6.1 in ./venv/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (6.2)\r\n",
      "Requirement already satisfied: pyzmq>=17 in ./venv/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (24.0.1)\r\n",
      "Requirement already satisfied: debugpy>=1.0 in ./venv/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (1.6.4)\r\n",
      "Requirement already satisfied: jupyter-client>=6.1.12 in ./venv/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets->pycaret) (7.4.7)\r\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in ./venv/lib/python3.10/site-packages (from jedi>=0.16->IPython->pycaret) (0.8.3)\r\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from jinja2<3.2,>=2.11.1->pandas-profiling>=2.8.0->pycaret) (2.1.1)\r\n",
      "Collecting llvmlite<0.40,>=0.39.0dev0\r\n",
      "  Using cached llvmlite-0.39.1-cp310-cp310-macosx_10_9_x86_64.whl (25.5 MB)\r\n",
      "Collecting smart-open>=1.8.1\r\n",
      "  Using cached smart_open-5.2.1-py3-none-any.whl (58 kB)\r\n",
      "Requirement already satisfied: ptyprocess>=0.5 in ./venv/lib/python3.10/site-packages (from pexpect>4.3->IPython->pycaret) (0.7.0)\r\n",
      "Requirement already satisfied: wcwidth in ./venv/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.11->IPython->pycaret) (0.2.5)\r\n",
      "Collecting typing-extensions>=4.1.0\r\n",
      "  Using cached typing_extensions-4.4.0-py3-none-any.whl (26 kB)\r\n",
      "Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests<2.29,>=2.24.0->pandas-profiling>=2.8.0->pycaret) (2022.9.24)\r\n",
      "Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests<2.29,>=2.24.0->pandas-profiling>=2.8.0->pycaret) (3.4)\r\n",
      "Collecting charset-normalizer<3,>=2\r\n",
      "  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)\r\n",
      "Collecting slicer==0.0.7\r\n",
      "  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)\r\n",
      "Requirement already satisfied: greenlet!=0.4.17 in ./venv/lib/python3.10/site-packages (from sqlalchemy<2,>=1.4.0->mlflow->pycaret) (2.0.1)\r\n",
      "Collecting patsy>=0.5.2\r\n",
      "  Using cached patsy-0.5.3-py2.py3-none-any.whl (233 kB)\r\n",
      "Collecting confection<1.0.0,>=0.0.1\r\n",
      "  Using cached confection-0.0.3-py3-none-any.whl (32 kB)\r\n",
      "Collecting blis<0.8.0,>=0.7.8\r\n",
      "  Using cached blis-0.7.9-cp310-cp310-macosx_10_9_x86_64.whl (6.1 MB)\r\n",
      "Requirement already satisfied: executing>=1.2.0 in ./venv/lib/python3.10/site-packages (from stack-data->IPython->pycaret) (1.2.0)\r\n",
      "Requirement already satisfied: pure-eval in ./venv/lib/python3.10/site-packages (from stack-data->IPython->pycaret) (0.2.2)\r\n",
      "Requirement already satisfied: asttokens>=2.1.0 in ./venv/lib/python3.10/site-packages (from stack-data->IPython->pycaret) (2.2.0)\r\n",
      "Collecting smmap<6,>=3.0.1\r\n",
      "  Using cached smmap-5.0.0-py3-none-any.whl (24 kB)\r\n",
      "Requirement already satisfied: jupyter-core>=4.9.2 in ./venv/lib/python3.10/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->pycaret) (5.1.0)\r\n",
      "Collecting PyWavelets\r\n",
      "  Using cached PyWavelets-1.4.1-cp310-cp310-macosx_10_13_x86_64.whl (4.4 MB)\r\n",
      "Requirement already satisfied: platformdirs>=2.5 in ./venv/lib/python3.10/site-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->pycaret) (2.5.4)\r\n",
      "Installing collected packages: typing-extensions, catalogue, threadpoolctl, tangled-up-in-unicode, srsly, smmap, scipy, PyWavelets, pydantic, networkx, murmurhash, multimethod, llvmlite, joblib, cymem, click, charset-normalizer, zipp, Werkzeug, wasabi, visions, typer, tqdm, tenacity, tabulate, smart-open, slicer, scikit-learn, requests, regex, pyjwt, preshed, patsy, oauthlib, numba, Mako, itsdangerous, imagehash, gitdb, confection, cloudpickle, blis, typeguard, thinc, statsmodels, sqlparse, spacy-loggers, spacy-legacy, sklearn, shap, seaborn, querystring-parser, PyYAML, pynndescent, pyarrow, protobuf, plotly, phik, pathy, numexpr, nltk, markdown, langcodes, importlib-metadata, htmlmin, gunicorn, graphviz, gitpython, gensim, future, funcy, Flask, docker, databricks-cli, colorlover, alembic, yellowbrick, xgboost, wordcloud, umap-learn, textblob, spacy, scikit-plot, pyod, pyLDAvis, pandas-profiling, mlxtend, mlflow, lightgbm, kmodes, imbalanced-learn, cufflinks, catboost, pycaret\r\n",
      "Successfully installed Flask-2.2.2 Mako-1.2.4 PyWavelets-1.4.1 PyYAML-6.0 Werkzeug-2.2.2 alembic-1.8.1 blis-0.7.9 catalogue-2.0.8 catboost-1.1.1 charset-normalizer-2.1.1 click-8.1.3 cloudpickle-2.2.0 colorlover-0.3.0 confection-0.0.3 cufflinks-0.17.3 cymem-2.0.7 databricks-cli-0.17.3 docker-6.0.1 funcy-1.17 future-0.18.2 gensim-4.2.0 gitdb-4.0.10 gitpython-3.1.29 graphviz-0.20.1 gunicorn-20.1.0 htmlmin-0.1.12 imagehash-4.3.1 imbalanced-learn-0.9.1 importlib-metadata-5.1.0 itsdangerous-2.1.2 joblib-1.2.0 kmodes-0.12.2 langcodes-3.3.0 lightgbm-3.3.3 llvmlite-0.39.1 markdown-3.4.1 mlflow-2.0.1 mlxtend-0.21.0 multimethod-1.9 murmurhash-1.0.9 networkx-2.8.8 nltk-3.7 numba-0.56.4 numexpr-2.8.4 oauthlib-3.2.2 pandas-profiling-3.5.0 pathy-0.10.0 patsy-0.5.3 phik-0.12.2 plotly-5.11.0 preshed-3.0.8 protobuf-4.21.10 pyLDAvis-3.3.1 pyarrow-10.0.1 pycaret-2.2.2 pydantic-1.10.2 pyjwt-2.6.0 pynndescent-0.5.8 pyod-1.0.6 querystring-parser-1.2.4 regex-2022.10.31 requests-2.28.1 scikit-learn-1.1.3 scikit-plot-0.3.7 scipy-1.9.3 seaborn-0.12.1 shap-0.41.0 sklearn-0.0.post1 slicer-0.0.7 smart-open-5.2.1 smmap-5.0.0 spacy-3.4.3 spacy-legacy-3.0.10 spacy-loggers-1.0.3 sqlparse-0.4.3 srsly-2.4.5 statsmodels-0.13.5 tabulate-0.9.0 tangled-up-in-unicode-0.2.0 tenacity-8.1.0 textblob-0.17.1 thinc-8.1.5 threadpoolctl-3.1.0 tqdm-4.64.1 typeguard-2.13.3 typer-0.7.0 typing-extensions-4.4.0 umap-learn-0.5.3 visions-0.7.5 wasabi-0.10.1 wordcloud-1.8.2.2 xgboost-1.7.1 yellowbrick-1.5 zipp-3.11.0\r\n",
      "\u001B[33mWARNING: You are using pip version 21.3.1; however, version 22.3.1 is available.\r\n",
      "You should consider upgrading via the '/Users/tangyuqi/Documents/Data Engineering/DataEngineering-HW4/venv/bin/python -m pip install --upgrade pip' command.\u001B[0m\r\n"
     ]
    }
   ],
   "source": [
    "# install packages\n",
    "!pip install polygon-api-client\n",
    "!pip install sqlalchemy\n",
    "!pip install pandas\n",
    "!pip install matplotlib\n",
    "!pip install numpy==1.22.3\n",
    "!pip install pycaret"
   ],
   "metadata": {
    "collapsed": false
   }
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
